/**
 * Внешний вид blockquote/цитаты (как в карточке материала): полоса слева и мягкий фон.
 * Используем и в просмотре, и в contentEditable — `&_blockquote`, чтобы срабатывало и внутри вложенных div.
 */
export const pvlProseBlockquoteClass =
    '[&_blockquote]:my-4 [&_blockquote]:rounded-r-lg [&_blockquote]:border-l-4 [&_blockquote]:border-emerald-200/80 [&_blockquote]:bg-emerald-50/40 [&_blockquote]:pl-4 [&_blockquote]:pr-3 [&_blockquote]:py-2.5 [&_blockquote]:text-slate-700 [&_blockquote>p]:mb-0 [&_blockquote>p+p]:mt-2';

/**
 * Общие стили богатого текста (материалы Сада, ответы ДЗ, тред с ментором) — единая типографика и абзацы.
 * Не ставим overflow-x-auto на корень — иначе обрезаются маркеры нумерованных списков.
 */
export const pvlMaterialBodyClass =
    `text-sm text-slate-700 leading-7 max-w-full [&_.pvl-doc-verbatim]:whitespace-pre-wrap [&_.pvl-doc-verbatim]:font-normal [&_.pvl-doc-verbatim]:text-slate-700 [&_.pvl-doc-verbatim]:leading-7 [&_.pvl-wiki-embed]:my-3 [&>h1]:mt-6 [&>h1]:mb-3 [&>h1]:text-xl [&>h1]:font-semibold [&>h1]:text-slate-900 [&>h1]:border-b [&>h1]:border-slate-200 [&>h1]:pb-2 [&>h2]:mt-5 [&>h2]:mb-2.5 [&>h2]:text-lg [&>h2]:font-semibold [&>h2]:text-slate-900 [&>h3]:mt-4 [&>h3]:mb-2 [&>h3]:text-base [&>h3]:font-semibold [&>h3]:text-slate-800 [&>h4]:mt-3 [&>h4]:mb-1.5 [&>h4]:text-base [&>h4]:font-semibold [&>h5]:mt-2 [&>h5]:mb-1 [&>h5]:text-sm [&>h5]:font-semibold [&>h6]:mt-2 [&>h6]:mb-1 [&>h6]:text-sm [&>h6]:font-semibold [&>p]:mb-3 [&>p]:leading-relaxed [&>ul]:my-3 [&>ul]:list-disc [&>ul]:list-outside [&>ul]:pl-6 [&>ul]:space-y-1 [&>ol]:my-3 [&>ol]:list-decimal [&>ol]:list-outside [&>ol]:pl-6 [&>ol]:space-y-1 [&_ul]:my-2 [&_ul]:list-disc [&_ul]:list-outside [&_ul]:pl-5 [&_ol]:my-2 [&_ol]:list-decimal [&_ol]:list-outside [&_ol]:pl-5 [&_li]:my-1 [&_li]:pl-0.5 ${pvlProseBlockquoteClass} [&>hr]:my-6 [&>hr]:border-slate-200 [&>pre]:whitespace-pre-wrap [&>pre]:rounded-xl [&>pre]:border [&>pre]:border-slate-200 [&>pre]:bg-slate-50 [&>pre]:p-3 [&_table]:my-4 [&_table]:block [&_table]:w-full [&_table]:max-w-none [&_table]:overflow-x-auto [&_table]:min-w-[min(100%,48rem)] [&_table]:border-collapse [&_table]:border [&_table]:border-slate-200 [&_table]:text-sm [&_th]:border [&_th]:border-slate-200 [&_th]:bg-slate-50/90 [&_th]:px-2 [&_th]:py-2 [&_th]:text-left [&_td]:border [&_td]:border-slate-200 [&_td]:px-2 [&_td]:py-2 [&_td]:align-top [&_strong]:font-semibold [&_em]:italic [&_a]:text-emerald-800 [&_a]:underline [&_img]:max-h-[min(80vh,32rem)] [&_img]:max-w-full [&_img]:rounded-lg [&_code]:rounded [&_code]:bg-slate-100 [&_code]:px-1 [&_code]:py-0.5 [&_code]:text-[0.9em]`;
