-- Chat messages table for CommunicationsView
-- Safe to re-run.

create table if not exists public.messages (
  id bigint generated by default as identity primary key,
  author_id uuid null,
  author_name text not null default 'Участник',
  text text not null,
  created_at timestamptz not null default now(),
  edited_at timestamptz null,
  deleted_at timestamptz null
);

create index if not exists messages_created_at_idx
  on public.messages (created_at desc);

create index if not exists messages_author_id_idx
  on public.messages (author_id);

alter table public.messages enable row level security;

grant select, insert on table public.messages to authenticated;

do $$
begin
  if not exists (
    select 1 from pg_policies
    where schemaname = 'public' and tablename = 'messages' and policyname = 'messages_select_authenticated'
  ) then
    create policy messages_select_authenticated
      on public.messages
      for select
      to authenticated
      using (auth.uid() is not null);
  end if;

  if not exists (
    select 1 from pg_policies
    where schemaname = 'public' and tablename = 'messages' and policyname = 'messages_insert_authenticated'
  ) then
    create policy messages_insert_authenticated
      on public.messages
      for insert
      to authenticated
      with check (
        auth.uid() is not null
        and (author_id is null or author_id = auth.uid())
      );
  end if;
end $$;

-- Allow realtime subscriptions in Supabase Realtime.
do $$
begin
  begin
    alter publication supabase_realtime add table public.messages;
  exception
    when duplicate_object then
      null;
    when undefined_object then
      null;
  end;
end $$;
