-- Fallback storage for web push subscriptions (non-Supabase setups).
-- Safe to re-run.

create table if not exists public.push_subscriptions (
  id bigint generated by default as identity primary key,
  user_id uuid null,
  endpoint text not null unique,
  keys jsonb not null default '{}'::jsonb,
  user_agent text null,
  is_active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists push_subscriptions_user_id_idx
  on public.push_subscriptions (user_id);

create index if not exists push_subscriptions_active_idx
  on public.push_subscriptions (is_active);

grant select, insert, update on table public.push_subscriptions to public;
grant usage, select on sequence public.push_subscriptions_id_seq to public;
