-- Create a table for news
create table news (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  title text not null,
  body text not null,
  image_url text,
  author_id uuid references auth.users,
  type text default 'general'
);

-- RLS
alter table news enable row level security;

create policy "News are viewable by everyone."
  on news for select
  using ( true );

create policy "Admins can insert news."
  on news for insert
  with check ( true ); -- You might want to restrict this to specific users/roles
