-- Create a table for public profiles
create table profiles (
  id uuid references auth.users not null primary key,
  updated_at timestamp with time zone,
  name text,
  role text default 'applicant',
  tree text,
  tree_desc text,
  seeds int default 0,
  city text,
  avatar_url text,
  directions text[],
  skills text[],
  offer text,
  unique_abilities text,
  join_date date,
  
  constraint username_length check (char_length(name) >= 3)
);

-- Set up Row Level Security (RLS)
-- See https://supabase.com/docs/guides/auth/row-level-security for more details.
alter table profiles enable row level security;

create policy "Public profiles are viewable by everyone."
  on profiles for select
  using ( true );

create policy "Users can insert their own profile."
  on profiles for insert
  with check ( auth.uid() = id );

create policy "Users can update own profile."
  on profiles for update
  using ( auth.uid() = id );

-- Create a table for practices
create table practices (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  title text not null,
  description text,
  author_id uuid references auth.users not null,
  category text,
  likes int default 0
);

alter table practices enable row level security;

create policy "Practices are viewable by everyone."
  on practices for select
  using ( true );

create policy "Users can insert their own practices."
  on practices for insert
  with check ( auth.uid() = author_id );

create policy "Users can update own practices."
  on practices for update
  using ( auth.uid() = author_id );

-- Create a table for meetings
create table meetings (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  user_id uuid references auth.users not null,
  date date not null,
  guests int default 0,
  income int default 0,
  keep_notes text, -- re-purposed as "What went well"
  change_notes text, -- re-purposed as "What to improve"
  
  -- Meetings 2.0 New Fields
  title text,
  status text default 'planned', -- planned, pending, completed, cancelled
  new_guests int default 0,
  scenario_id text,
  fail_reason text,
  checklist jsonb default '[]'::jsonb,
  tags text[],
  rescheduled_to bigint references meetings(id)
);

alter table meetings enable row level security;

create policy "Users can view own meetings."
  on meetings for select
  using ( auth.uid() = user_id );

create policy "Users can insert own meetings."
  on meetings for insert
  with check ( auth.uid() = user_id );

create policy "Users can update own meetings."
  on meetings for update
  using ( auth.uid() = user_id );

create policy "Users can delete own meetings."
  on meetings for delete
  using ( auth.uid() = user_id );

-- Create a table for notifications
create table notifications (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  user_id uuid references auth.users not null,
  from_name text,
  type text,
  message text,
  read boolean default false
);

alter table notifications enable row level security;

create policy "Users can view own notifications."
  on notifications for select
  using ( auth.uid() = user_id );

create policy "Users can update own notifications."
  on notifications for update
  using ( auth.uid() = user_id );
-- Create a table for goals
create table goals (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  user_id uuid references auth.users not null,
  title text not null,
  description text,
  completed boolean default false,
  completed_at timestamp with time zone,
  related_tags text[],
  linked_meeting_id bigint references meetings(id)
);

alter table goals enable row level security;

create policy "Users can view own goals."
  on goals for select
  using ( auth.uid() = user_id );

create policy "Users can insert own goals."
  on goals for insert
  with check ( auth.uid() = user_id );

create policy "Users can update own goals."
  on goals for update
  using ( auth.uid() = user_id );

create policy "Users can delete own goals."
  on goals for delete
  using ( auth.uid() = user_id );

-- Add tags and reschedule fields to meetings if not exists (doing it via alter for existing table)
-- Note: In a real migration we would use alter table, but here we update the definition for future.
-- IMPORTANT: The user must run this SQL manually or we trust they handle it.
-- For the agent to support it, we assume the schema file reflects the desired state.
